name: TaskFlow CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend Docker image
        run: |
          docker build -t taskflow-backend \
          -f Dockerfile.backend .

      - name: Build frontend Docker image
        run: |
          docker build -t taskflow-frontend \
          -f Dockerfile.frontend .
